EXECUTE drop_app_tables;

CREATE TABLE appointment_statuses (
    id   NUMBER CONSTRAINT appointment_statuses_PK PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE doctor_types (
    id   NUMBER CONSTRAINT doctor_types_PK PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE test_types (
    id   NUMBER CONSTRAINT test_type_PK PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE tests (
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT test_PK PRIMARY KEY,
    test_type_id NUMBER NOT NULL REFERENCES test_types(id),
    result       VARCHAR2(100) NOT NULL
);

CREATE TABLE wards (
    id   NUMBER CONSTRAINT ward_PK PRIMARY KEY,
    name VARCHAR2(50) NOT NULL
);

CREATE TABLE accounts (
    id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT accounts_PK PRIMARY KEY,
    login    VARCHAR2(20) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL
);

CREATE TABLE patients (
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT patients_PK PRIMARY KEY,
    birthdate DATE NOT NULL,
    name      VARCHAR2(50) NOT NULL,
    surname   VARCHAR2(50) NOT NULL,
    gender    CHAR(1) NOT NULL,
    CONSTRAINT patient_gender CHECK (gender IN ('F', 'M'))
);

CREATE TABLE doctors (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT doctors_PK PRIMARY KEY,
    name           VARCHAR2(50) NOT NULL,
    surname        VARCHAR2(50) NOT NULL,
    date_employed  DATE
);

CREATE TABLE doctor_ward (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT doctor_ward_PK PRIMARY KEY,
    doctor_id   NUMBER NOT NULL REFERENCES doctors(id),
    ward_id     NUMBER NOT NULL REFERENCES wards(id)
);

CREATE TABLE doctor_schedules (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT doctor_schedules_PK PRIMARY KEY,
    doctor_id      NUMBER NOT NULL REFERENCES doctors(id),
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL
);

CREATE TABLE doctor_specialties (
    doctor_id      NUMBER NOT NULL,
    doctor_type_id NUMBER NOT NULL,
    CONSTRAINT doctor_specialties_PK PRIMARY KEY (doctor_id, doctor_type_id)
);

CREATE TABLE appointments (
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT appointment_PK PRIMARY KEY,
    datetime              DATE NOT NULL,
    patients_note         VARCHAR2(1000),
    doctor_id             NUMBER NOT NULL REFERENCES doctors(id) ON DELETE SET NULL,
    appointment_status_id NUMBER NOT NULL REFERENCES appointment_statuses(id),
    patient_id            NUMBER NOT NULL REFERENCES patients(id) ON DELETE SET NULL,
    appointment_type      CHAR(4)
    CONSTRAINT appointment_type_selector CHECK(appointment_type IN ('EXAM', 'CONS'))
);

CREATE TABLE consultations (
    id  NUMBER CONSTRAINT consultations_PK PRIMARY KEY,
    CONSTRAINT consultations_id_FK FOREIGN KEY (id) REFERENCES appointments(id)
);

CREATE TABLE examinations (
    id      NUMBER CONSTRAINT examinations_PK PRIMARY KEY,
    test_id NUMBER CONSTRAINT examinations_tests_FK REFERENCES tests(id),
    CONSTRAINT examinations_id_FK FOREIGN KEY (id) REFERENCES appointments(id)
);

CREATE TABLE medical_documents (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000 CONSTRAINT medical_documents_PK PRIMARY KEY,
    appointment_id  NUMBER NOT NULL CONSTRAINT medical_documents_appointments_FK REFERENCES appointments(id),
    type            CHAR(4),
    body            CLOB,
    CONSTRAINT medical_documents_type_selector CHECK(type IN ('NOTE', 'PRES'))
);

