package pl.edu.pw.bd.hospital.entity;
// Generated May 14, 2025, 10:20:46 PM by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * AppointmentStatus generated by hbm2java
 */
@Entity
@Table(schema="sys", name="appointment_statuses"
)
public class AppointmentStatus  implements java.io.Serializable {


     private Long id;
     private String name;
     private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public AppointmentStatus() {
    }

	
    public AppointmentStatus(Long id, String name) {
        this.id = id;
        this.name = name;
    }
    public AppointmentStatus(Long id, String name, Set<Appointment> appointments) {
       this.id = id;
       this.name = name;
       this.appointments = appointments;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="appointmentStatus")
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }




}


