package pl.edu.pw.bd.hospital.entity;
// Generated May 14, 2025, 10:20:46 PM by Hibernate Tools 5.6.15.Final


import java.math.BigInteger;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * MedicalDocument generated by hbm2java
 */
@Entity
@Table(schema="sys", name="medical_documents")
public class MedicalDocument  implements java.io.Serializable {


     private BigInteger id;
     private Appointment appointment;
     private Character type;

    public MedicalDocument() {
    }

	
    public MedicalDocument(BigInteger id, Appointment appointment) {
        this.id = id;
        this.appointment = appointment;
    }
    public MedicalDocument(BigInteger id, Appointment appointment, Character type) {
       this.id = id;
       this.appointment = appointment;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getId() {
        return this.id;
    }
    
    public void setId(BigInteger id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPOINTMENT_ID", referencedColumnName="id", nullable=false)
    public Appointment getAppointment() {
        return this.appointment;
    }
    
    public void setAppointment(Appointment appointment) {
        this.appointment = appointment;
    }

    @Column(name="type", length=1)
    public Character gettype() {
        return this.type;
    }
    
    public void settype(Character type) {
        this.type = type;
    }
}


