package pl.edu.pw.bd.hospital.entity;
// Generated May 14, 2025, 10:20:46 PM by Hibernate Tools 5.6.15.Final


import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * TestType generated by hbm2java
 */
@Entity
@Table(schema="sys", name="test_types")
public class TestType  implements java.io.Serializable {


     private BigInteger id;
     private String name;
     private Set<Test> tests = new HashSet<Test>(0);

    public TestType() {
    }

	
    public TestType(BigInteger id, String name) {
        this.id = id;
        this.name = name;
    }
    public TestType(BigInteger id, String name, Set<Test> tests) {
       this.id = id;
       this.name = name;
       this.tests = tests;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getId() {
        return this.id;
    }
    
    public void setId(BigInteger id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testType")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }




}


